#!/usr/bin/env bash

printf "\033[0;34m"

echo "Cleaning previous configs"
rm -rf .config/ .repos/ .scripts/ .boilerplates/
mkdir -p .config/{dunst,qutebrowser,gtk-2.0,gtk-3.0,nvim,zathura,mpv,spicetify} .repos

echo "Copying configs"

# Scripts
cp -r "$HOME"/.scripts/ .

# Configs
cp "$HOME"/.config/dunst/dunstrc .config/dunst/
cp "$HOME"/.config/qutebrowser/config.py .config/qutebrowser/
cp "$HOME"/.config/gtk-2.0/* .config/gtk-2.0/
cp "$HOME"/.config/gtk-3.0/* .config/gtk-3.0/
cp "$HOME"/.config/nvim/init.vim .config/nvim/
cp "$HOME"/.config/zathura/zathurarc .config/zathura/
cp "$HOME"/.config/mpv/mpv.conf .config/mpv/
cp "$HOME"/.config/uncrustify.cfg .config/
cp -r "$HOME"/.config/spicetify/{config.ini,Themes/} .config/spicetify/

# Inits
cp "$HOME"/.bash_profile "$HOME"/.bashrc "$HOME"/.xinitrc "$HOME"/.Xresources .
cp -r "$HOME"/.lein .

# Boilerplates
cp -r "$HOME"/.boilerplates .

# Crypto keys etc.
echo "Uploading keys"
scp -rq "$HOME"/.crypto/ root@10.0.0.33:/mnt/ssd/

# Repos
echo "Cleaning suckless configs"
cp -r "$HOME"/.repos/* .repos/
find .repos/ -type d -name ".git" -exec rm -rf {} +
find .repos/ -type f -exec sh -c "file -i '{}' | grep -q 'charset=binary'" \; -delete

# Installed programs
echo "Getting package list"
pacman -Qqe > packages.txt

printf "\nChanged files:\n"
printf "\033[0;32m"
git status -s | cut -c4-

printf "\033[0m"
