#!/usr/bin/env bash

rm -rf .config/ .repos/ .scripts/ .boilerplates/
mkdir -p .config/{dunst,gtk-2.0,gtk-3.0,nvim,zathura,mpv} .repos

# Scripts
cp -r "$HOME"/.scripts/ .

# Configs
cp "$HOME"/.config/dunst/dunstrc .config/dunst/
cp "$HOME"/.config/gtk-2.0/* .config/gtk-2.0/
cp "$HOME"/.config/gtk-3.0/* .config/gtk-3.0/
cp "$HOME"/.config/nvim/init.vim .config/nvim/
cp "$HOME"/.config/zathura/zathurarc .config/zathura/
cp "$HOME"/.config/mpv/mpv.conf .config/mpv/
cp "$HOME"/.config/uncrustify.cfg .config/

# Boilerplates
cp -r "$HOME"/.boilerplates .

# Crypto keys etc.
scp -r "$HOME"/.crypto/ root@10.0.0.33:/mnt/ssd/

# Repos
cp -r "$HOME"/.repos/* .repos/
find .repos/ -type d -name ".git" -exec rm -rf {} +

# Inits
cp "$HOME"/.bash_profile "$HOME"/.bashrc "$HOME"/.xinitrc "$HOME"/.Xresources .
cp -r "$HOME"/.lein .

# Installed programs
pacman -Qqe > packages.txt

git status
