#!/usr/bin/env sh

make --always-make --dry-run | grep -w 'gcc' | grep -w '\-c' | jq -nR '[inputs|{directory:".", command:., file: match(" [^ ]+$").string[1:]}]' > compile_commands.json

ctags -R --exclude=.git --exclude=out .

make && ./out/name "$@"
