#!/bin/bash

if grep -Fxq "##START" /etc/hosts; then
	sudo sed -i "/##START/,/##END/s/#\(.\)/\1/" /etc/hosts
	notify-send "Enabled adblock!"
else
	sudo sed -i "/#START/,/#END/s/./#&/" /etc/hosts
	notify-send "Disabled adblock!"
fi
