#!/usr/bin/env sh

notify-send -u critical "Waiting for internet connection..."
while ! ping -qc1 8.8.8.8 ; do sleep 0.1 ; done
notify-send -u critical "Found network!"

exec qutebrowser &
exec st &

exec telegram-desktop &
exec signal-desktop &
exec discord &
exec whatsapp-nativefier-dark &
exec thunderbird &

exec spotify
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play

notify-send -u critical "Welcome back, Melvin!"
