#!/bin/bash
#[ -z "$5" ] && echo "Usage: $0 <image> <x> <y> <z> <max height> <max width>" && exit
source "`ueberzug library`"

ImageLayer 0< <(
	ImageLayer::add [identifier]="example0" [x]="0" [y]="0" [max_width]="30" [max_height]="30" [path]="$1"
	read
)
