#!/bin/sh

setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl -option "caps:swapescape"
xmodmap -e "keysym Menu = Super_R"
xset r rate 300 50

xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0
xinput set-prop "pointer:Logitech MX Master 2S" "libinput High Resolution Wheel Scroll Enabled" 0
xinput set-prop "TPPS/2 Elan TrackPoint" "libinput Accel Speed" 0.4
xinput set-prop "TPPS/2 Elan TrackPoint" "libinput Accel Profile Enabled" 1 0
