#!/bin/env bash

export XAUTHORITY=/home/melvin/.Xauthority
export DISPLAY=:0
export XDG_RUNTIME_DIR=/run/user/1000
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

notify-send "Eine Stunde ist rum!" "Vielleicht eine kleine Pause?"
